# Generated by Django 2.2.14 on 2020-07-07 18:32

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='headers',
            field=wagtail.core.fields.StreamField([('h_bannerblock', wagtail.core.blocks.StructBlock([])), ('h_headlineblock', wagtail.core.blocks.StructBlock([]))], null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sections',
            field=wagtail.core.fields.StreamField([('s_mainsection', wagtail.core.blocks.StructBlock([])), ('s_sidesection', wagtail.core.blocks.StructBlock([])), ('s_coffeblock', wagtail.core.blocks.StructBlock([])), ('s_smallblock', wagtail.core.blocks.StructBlock([('charblock', wagtail.core.blocks.CharBlock()), ('textblock', wagtail.core.blocks.TextBlock()), ('emailblock', wagtail.core.blocks.EmailBlock())])), ('s_bigblock', wagtail.core.blocks.StructBlock([('integerblock', wagtail.core.blocks.IntegerBlock()), ('floatblock', wagtail.core.blocks.FloatBlock()), ('decimalblock', wagtail.core.blocks.DecimalBlock()), ('regexblock', wagtail.core.blocks.RegexBlock(regex='')), ('urlblock', wagtail.core.blocks.URLBlock()), ('booleanblock', wagtail.core.blocks.BooleanBlock()), ('dateblock', wagtail.core.blocks.DateBlock())])), ('s_tallblock', wagtail.core.blocks.StructBlock([('timeblock', wagtail.core.blocks.TimeBlock()), ('datetimeblock', wagtail.core.blocks.DateTimeBlock()), ('richtextblock', wagtail.core.blocks.RichTextBlock()), ('rawhtmlblock', wagtail.core.blocks.RawHTMLBlock()), ('blockquoteblock', wagtail.core.blocks.BlockQuoteBlock()), ('choiceblock', wagtail.core.blocks.ChoiceBlock(choices=[])), ('pagechooserblock', wagtail.core.blocks.PageChooserBlock())])), ('s_lightblock', wagtail.core.blocks.StructBlock([('documentchooserblock', wagtail.documents.blocks.DocumentChooserBlock()), ('imagechooserblock', wagtail.images.blocks.ImageChooserBlock()), ('snippetchooserblock', wagtail.snippets.blocks.SnippetChooserBlock(target_model='home.Snippet')), ('embedblock', wagtail.embeds.blocks.EmbedBlock()), ('staticblock', wagtail.core.blocks.static_block.StaticBlock())]))], null=True),
        ),
    ]
