# Generated by Django 2.2.14 on 2020-07-08 19:14

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.blocks.static_block
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200708_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='headers',
        ),
        migrations.AddField(
            model_name='homepage',
            name='bigintegerfield',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='booleanfield',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='charfield',
            field=models.CharField(max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='datefield',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='datetimefield',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='decimalfield',
            field=models.DecimalField(decimal_places=5, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='durationfield',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='emailfield',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='filefield',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='filepathfield',
            field=models.FilePathField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='floatfield',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='genericipaddressfield',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='imagefield',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='integerfield',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nullbooleanfield',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='homepage',
            name='positiveintegerfield',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='positivesmallintegerfield',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slugfield',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='smallintegerfield',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='textfield',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='timefield',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='urlfield',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='uuidfield',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sections',
            field=wagtail.core.fields.StreamField([('s_smallblock', wagtail.core.blocks.StructBlock([('charblock', wagtail.core.blocks.CharBlock()), ('textblock', wagtail.core.blocks.TextBlock()), ('emailblock', wagtail.core.blocks.EmailBlock())])), ('s_bigblock', wagtail.core.blocks.StructBlock([('integerblock', wagtail.core.blocks.IntegerBlock()), ('floatblock', wagtail.core.blocks.FloatBlock()), ('decimalblock', wagtail.core.blocks.DecimalBlock()), ('regexblock', wagtail.core.blocks.RegexBlock(regex='')), ('urlblock', wagtail.core.blocks.URLBlock()), ('booleanblock', wagtail.core.blocks.BooleanBlock()), ('dateblock', wagtail.core.blocks.DateBlock())])), ('s_tallblock', wagtail.core.blocks.StructBlock([('timeblock', wagtail.core.blocks.TimeBlock()), ('datetimeblock', wagtail.core.blocks.DateTimeBlock()), ('richtextblock', wagtail.core.blocks.RichTextBlock()), ('rawhtmlblock', wagtail.core.blocks.RawHTMLBlock()), ('blockquoteblock', wagtail.core.blocks.BlockQuoteBlock()), ('choiceblock', wagtail.core.blocks.ChoiceBlock(choices=[('apples', 'Apple'), ('bananas', 'Bananas')]))])), ('s_lightblock', wagtail.core.blocks.StructBlock([('documentchooserblock', wagtail.documents.blocks.DocumentChooserBlock()), ('imagechooserblock', wagtail.images.blocks.ImageChooserBlock()), ('snippetchooserblock', wagtail.snippets.blocks.SnippetChooserBlock(target_model='home.Snippet')), ('embedblock', wagtail.embeds.blocks.EmbedBlock()), ('staticblock', wagtail.core.blocks.static_block.StaticBlock())]))], null=True),
        ),
    ]
