# Generated by Django 2.2.14 on 2020-07-08 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200708_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='uuidfield',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
