# Generated by Django 2.2.14 on 2020-07-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200708_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='filepathfield',
        ),
    ]
